/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js projects and kept here so TypeScript tools
// understand Next-specific imports before dependencies are installed.
